name: magic8ball
description: "A new Flutter project."
publish_to: 'none' # Prevents accidental publishing to pub.dev
version: 1.0.0+1
environment:
  sdk: '>=3.2.6 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.1
flutter:
  assets:
    - Images/
  uses-material-design: true
